Bar Charts
========================================================
(See the source code and more examples here: https://github.com/plotly/knitr-demos)

In `ggplot2`, you plot bar charts using `geom_bar` plus `stat_identity`. 

```{r}
library(ggplot2)
library(devtools)
install_github("ropensci/plotly")
# Initialize a plotly object to sign in to your Plotly API account
py <- plotly('R-demos', 'p9g4f35ytd')
```

```{r}
# Consider the following data frame
researchers <- data.frame(country=c("Canada", "Canada", "Germany", "USA"),
                          name=c("Warren", "Andreanne", "Stefan", "Toby"),
                          papers=c(23, 14, 37, 20),
                          field=c("Math", "Bio", "Bio", "Math"))

# Let us plot the number of papers (y) per country (x) splitting by field
gg.dodge <- ggplot(researchers, aes(x=country, y=papers, fill=field)) +
  geom_bar(stat="identity", position="dodge")
```

In R your plot looks like this:

```{r fig.width=7, fig.height=6}
print(gg.dodge)
```

Send it to Plotly!

```{r, plotly=TRUE, width=600, height=600}
py$ggplotly(gg.dodge)
```

Oh, the default colors are different.  Let us change the colors the way we like using Plotly's UI.  Say we are happy with the following:

```{r, plotly=TRUE, width=600, height=600}
py$embed("https://plot.ly/~R-demos/11/papers-vs-country/")
```
